openapi: '3.0.2'
info:
  title: API Users
  description: API para listar os usuários cadastrados dentro do sistema
  version: '1.0'
externalDocs:
  description: Link para documentação do Swagger
  url: https://swagger.io/solutions/api-documentation/
servers:
  - url: http://localhost:5000
paths:
  /api:
    get:
      summary: Retorna todos os usuários cadastrados
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    occupation:
                      type: string
                    city:
                      type: string
    post:
      summary: Cria um novo usuário
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                occupation:
                  type: string
                city:
                  type: string
      responses:
        '201':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  occupation:
                    type: string
                  city:
                    type: string
  /api/{id}:
    get:
      summary: Retorna um usuário a partir de um ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                    name:
                      type: string
                    occupation:
                      type: string
                    city:
                      type: string
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              example: "Usuário não encontrado"
