name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

  env:
    GITHUB_TOKEN: ${{ secrets.AZURE_TOKEN }}

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      whit:
        node-version: 12.18.x
    
    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline

    - name: Run Jest tests
      run: yarn test