openapi: "3.0.2"
info:
  title: API Title
  description: API para listar os usuários cadastrados no github
  version: "1.0"
externalDocs:
  description: Link para documentação oficial da API do github
  url: https://api.github.com/
servers:
  - url: http://localhost:3000/
paths:
  /api:
    get:
      summary: Retorna todos os usuários cadastrados
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    login:
                      type: string
                    id:
                      type: integer
                    node_id:
                      type: string
                    avatar_url:
                      type: string
    post:
      summary: Cria um novo usuário
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Usuário deletado com sucesso

  /api/{id}:
    delete:
      summary: Deleta um usuário a partir de um id informado
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Usuário deletado com sucesso

