name: ci

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Olá Mundo!
      run: echo 'Olá Mundo!'
